### PR TITLE
changed theme, updated some images, fixed some image routes, renames …

### PR DESCRIPTION
**Pull request by ian-bateman**
…some files, coding style fixes

### CODE REVIEW

**Comment by jason-feng** [comment]
@ian-bateman i don't think you should be working on designs, especially for logos, when as a team we haven't made a decision yet

**Comment by ian-bateman** [comment]
Was just seeing how some stuff looked yesterday -- it's like 3 things I changed

**Comment by jason-feng** [comment]
@ian-bateman my comment is about the logo in the PR, as well as your past 10-15 commits or so, which are largely style changes. it's more important have functionality in the site, and worry about design later. if we want to meet our goal of having a rudimentary site where we can actually make an order and have it appear on the enterprise side

**Comment by ian-bateman** [comment]
yep I know functionality is more important -- moving onto other stuff now -- point taken :)

**Pull request merged**
